### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by AndyTheNerd** [aalises/age-of-empires-II-api#15]
Hey guys, looks like the API is down. 

https://age-of-empires-2-api.herokuapp.com/
![image](https://user-images.githubusercontent.com/30298320/94450981-e89adb00-017b-11eb-8fd5-81fc3b4419a5.png)

**Comment by aalises** [comment]
Unfortunately ran out of free dynos in Heroku for September due to usage (free plan). should be back up in October... feel free to change the provider/deployment configuration to another service that allows more usage e.g. AWS Lambda.
