### ISSUE TITLE
Free hosting idea

### ISSUE THREAD

**Issue by jpillora** [aalises/age-of-empires-II-api#20]
From the API spec, it appears it only supports GET all records, or one record by type. Therefore, this dataset could be traversed and all possible queries could be written as JSON files. Then, using Github pages or Cloudflare pages, you could serve all these JSON files for free on a GH/CF domain, or on a custom domain you provide.

Also, if the clients of this data are only web browsers, then you could use this strategy https://phiresky.github.io/blog/2021/hosting-sqlite-databases-on-github-pages/ to async query a static hosted (free) SQLite DB

**Comment by aalises** [comment]
Yes, there's no need for the SQLite database really, as we are effectively serving static data... if you are feeling like it @jpillora , you could make an MR that deploys to github pages using some action e.g. [this one](https://github.com/marketplace/actions/deploy-to-github-pages) and gets rid of the database.

**Comment by jpillora** [comment]
No time unfortunately, just thought I'd throw the idea out there :+1:
