### ISSUE TITLE
URL dead

### ISSUE THREAD

**Issue by themnmlst** [aalises/age-of-empires-II-api#23]
This url doesnt work anymore. 
https://age-of-empires-2-api.herokuapp.com

**Comment by Lobaton2020** [comment]
Heroku has stopped the free tire

**Comment by jshih2001** [comment]
Is their a new URL for this I need to finish my project on Postman

**Comment by themnmlst** [comment]
Stale. I'm closing this issue.

**Comment by themnmlst** [comment]
.
