### ISSUE TITLE
Incorrect Model for Civilization 

### ISSUE THREAD

**Issue by zmeriksen** [aalises/age-of-empires-II-api#8]
![Screen Shot 2019-12-14 at 4 45 36 PM](https://user-images.githubusercontent.com/8268288/70855491-28b0fb80-1e91-11ea-8054-1ddfd038003f.png)

## Issue
```
let unique_unit: String
let unique_tech: String
```

## Should be
```
let unique_unit: [String]
let unique_tech: [String]
```

# Correct Model
```
struct Civilization: Codable {
    let id: Int
    let name: String
    let expansion: String
    let army_type: String
    let unique_unit: [String]
    let unique_tech: [String]
    let team_bonus: String
    let civilization_bonus: [String]
}
```

**Comment by aalises** [comment]
Hello @zmeriksen ! thanks for pointing that out. The model is indeed correct on the API but not on the documentation (as it's not automatically generated based on the models). Do you have the capacity to do an MR fixing it? I can do it if not...

**Comment by aalises** [comment]
Hello @zmeriksen ! thanks for pointing that out. The model is indeed correct on the API but not on the documentation (as it's not automatically generated based on the models). Just pushed the fix ^^
